cieslarmichal/faker-cxx

include/faker-cxx/Lorem.h, src/Lorem.cpp
Extremely minuscule pull request, but I figured you'd want this in main ASAP.
Removed the requirement of boost::algorithm from lorem by using stringstreams to perform the join of words.
=> :heavy_minus_sign: Removed boost requirements from the Lorem module

include/faker-cxx/Color.h, src/modules/color/Color.cpp, src/modules/color/ColorTest.cpp
add hsl() function in Color module to generate random color in hsl format. Supports alpha and no-alpha colors.
=> add hsl-function to color module

include/faker-cxx/Color.h, src/modules/color/Color.cpp, src/modules/color/ColorTest.cpp
Added the LCH to color module (you can ignore the name of the branch, it says ich because I misread in the beginning but the code uses lch and the commit message as well).
=> Add lch function to Color module

CMakeLists.txt, README.md, include/faker-cxx/Image.h, include/faker-cxx/Internet.h, include/faker-cxx/types/ImageCategory.h, src/modules/image/Image.cpp, src/modules/image/ImageTest.cpp, src/modules/internet/Internet.cpp, src/modules/internet/InternetTest.cpp
- Introducing Image module
- Moving image Url generating from Internet module to Image module
closes #220
=> Image module

include/faker-cxx/String.h, include/faker-cxx/types/RandomGenerator.hpp, src/modules/string/String.cpp, src/modules/string/StringTest.cpp
Create RandomGenerator class.
Update uuid function to take in a RandomGenerator class as parameter.
#234
=> Feature/update UUID function to take optional random generator

include/faker-cxx/Helper.h, src/modules/helper/Helper.cpp
We already had a function `Helper::shuffle()` that can be use for shuffling a vector of objects but it wasn't possible to use it for a std::string and shuffle it chars
`Helper::shuffleString()` can be use to generate random permutations of a given std::string
=> feature: Implemented `Helper::shuffleString()` in `Helper` module

src/modules/git/GitTest.cpp
A conversion warning in GitTest.cpp was preventing compilation using MinGW on Windows.
=> Fix conversion error in GitTest.cpp

include/faker-cxx/String.h, src/modules/string/String.cpp, src/modules/string/StringTest.cpp
I overloaded these functions so that if user don't want to use string guarantees, they wont have to deal with an unnecessary parameter of `GuaranteeMap`.
Let me know if you like it this way or not, I will work on other functions accordingly.
=> refactor: Overloaded `String::binary()` and `String::octal()`

docs/apple_clang++_compilation_guide.md
**Add Compilation Guide for Apple Clang++ to Documentation:**
This pull request addresses issue #317. The goal is to add a detailed compilation guide for Apple Clang++ to the project's documentation. This guide is similar to the existing one for Clang++ and will be placed in a separate file within the `docs` directory.
Key Changes:
- Created a new Markdown file `Apple_Clang_Compilation_Guide.md` in the `docs` directory.
- The guide includes detailed instructions for installing Apple Clang++, preparing the build environment, setting up CMake, and building the project using Apple Clang++
=> docs:add compilation guide for apple clang++ (Issue #317)

README.md, docs/clang++_complilation_guide.md
**Title:** Move Clang++ Compilation Guide to Separate Doc in docs/
**Description:**
This pull request addresses Issue #316. It involves moving the existing clang++ compilation instructions from README.md to a new file in the docs/ directory. The changes include:
=> docs:move clang++ compilation guide to docs (Issue #316)

include/faker-cxx/String.h, src/modules/string/String.cpp, src/modules/string/StringTest.cpp, src/modules/string/data/Characters.h
=> feature: Implemented string guarantee for `String::numeric()`

include/faker-cxx/String.h
This is a minor improvement for people that work under the OS Windows and happen to include both `Windows.h` and `include/faker-cxx/String.h`. The header `Windows.h` might define the macros `min` and `max` which then leads to a compilation error in line 25 and 26 in the `CharCount` class.
=> Make sure that min and max do not collide with Windows.h macros

include/faker-cxx/types/BicCountry.h, src/modules/finance/FinanceTest.cpp, src/modules/finance/data/BankIndentifiersCodes.h
Added following countries to BIC in Finance. 
- US
- UK
- Germany
- Romania
- France
- Italy
- Spain
- Netherlands
- India
I don't think there was a way to have the test be under FinanceTest and still have it use `BicCountry` as the param. It's late, if it needs fixing please tell me and I'll fix it tomorrow.
=> Expanded BIC Countries

README.md
The current links for the guides in the read me result in 404 not found
Updated the links to fix this issue
=> update links for compilation guides

include/faker-cxx/types/AddressCountry.h, src/modules/location/Location.cpp, src/modules/location/LocationTest.cpp, src/modules/location/data/CountryAddresses.h, src/modules/location/data/australia/AustraliaAddresses.h, src/modules/location/data/brazil/BrazilAddresses.h, src/modules/location/data/brazil/BrazilCitySuffixes.h, src/modules/location/data/brazil/BrazilStates.h, src/modules/location/data/brazil/BrazilStreetSuffixes.h, src/modules/location/data/czech/CzechAddresses.h, src/modules/location/data/denmark/DenmarkAddresses.h, src/modules/location/data/france/FranceAddresses.h, src/modules/location/data/germany/GermanyAddresses.h, src/modules/location/data/india/IndiaAddresses.h, src/modules/location/data/italy/ItalyAddresses.h, src/modules/location/data/poland/PolandAddresses.h, src/modules/location/data/russia/RussiaAddresses.h, src/modules/location/data/spain/SpainAddresses.h, src/modules/location/data/ukraine/UkraineAddresses.h, src/modules/location/data/usa/UsaAddresses.h
The PR:
- Added location address data from Brazil #146.
- Added corresponding tests.
- Added `cityFormats`, `cityPrefixes`, and `citySuffixes` fields for `CountryAddresses`, modified other countries.
PR passed all the tests in my local.
Data is taken from [faker-js](https://github.com/faker-js/faker/tree/next/src/locales/pt_BR/location).
=> Add addresses in Brazil 🇧🇷

include/faker-cxx/Color.h, src/modules/color/Color.cpp, src/modules/color/ColorTest.cpp
=> Add lab function to color module

include/faker-cxx/Color.h, src/modules/color/Color.cpp, src/modules/color/ColorTest.cpp
Added yuv function to Color module and unit-test
=> Added yuv function to Color module

include/faker-cxx/Helper.h, src/modules/helper/HelperTest.cpp
Refactored weightArrayElement and Added unit-tests (https://github.com/cieslarmichal/faker-cxx/issues/496)
=> Refactored weightArrayElement

src/modules/date/Date.cpp, src/modules/date/DateTest.cpp
Fixed Date::time() method to use {:02} formatting for standard 2-digit (24h) time format, added unit test for testing against length of string
=> fixed Date::time formatting

.github/workflows/linux-clang-build.yml, .github/workflows/linux-gxx-build.yml, .github/workflows/macos-clang-build.yml, .github/workflows/windows-msvc-build.yml
Referring to issue: https://github.com/cieslarmichal/faker-cxx/issues/534
I've pinned the macos runner version to use macos-14 instead of macos-latest to avoid future incompatibilities. Refer to this page for runner update notes: https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
Changes:
- Add workflow_dispatch to be able to manually test these workflows
- Use `clang++` instead of the full clang++ path when configuring CMAKE.
- Brew installed clang++ to a different path, so updated that
The macos workflow sets up the clang++ path, and CMAKE is configured correctly here: https://github.com/AdamJovanovic/faker-cxx/actions/runs/8994676880/job/24708486690
=> Issue534 macos14 workflow upversion

CMakeLists.txt, src/common/FormatHelper.h
This PR changes the way how std::format is consumed, instead of setting a specific compiler version in CMake, it uses [CheckIncludeFileCXX](https://cmake.org/cmake/help/latest/module/CheckIncludeFileCXX.html) to detect if format can be imported from system (the compiler is configured already). In case finding `#include <format>` available, CMake will define `HAS_STD_FORMAT` and this variable will be used to define the logic of using libfmt or std format.
The advantage here is keeping the feature compiler agnostic, so in case the compiler X supports std format already, it will be used by default always. 
Second, the logic is centralized, CMake will check and define the state, so the header c++ has no double check for compiler version, etc.
I also replaced `CMAKE_CXX_STANDARD` by …
=> Use CMake to detect if std format is available

.github/workflows/linux-clang-build.yml, cmake/cmake-coverage.cmake
This PR fixes the current build on Linux using Clang.
Plus, it update Clang version 18, available in Ubuntu 24.04.
The Runner provided by Github action has LLVM 18 installed already, so don't need to bother installing basic stuff, like CMake. Only Ninja is really not installed by default.
=> Fix clang build

.github/workflows/linux-gxx-build.yml, CMakeLists.txt, README.md
Add support to use external dependencies instead of vendorized ones. The new CMake option `USE_SYSTEM_DEPENDENCIES`, uses `find_package` to include (mandatory) fmt and gtest. In case that option is enabled, and the compiler has std::format supported, CMake will use the external dependencies, because the user configured it explicitly.
Added a new CI job to validate the configuration.
closes #546
=> Add external dependencies option

CMakeLists.txt, include/faker-cxx/Weather.h, src/modules/weather/Weather.cpp, src/modules/weather/WeatherData.cpp, src/modules/weather/WeatherData.h, tests/modules/weather/WeatherTest.cpp
This update is done in reference to issue #581
=> refactor weather data

.gitignore, CMakeLists.txt, cmake/CompilerWarnings.cmake, tests/CMakeLists.txt
Adding compiler warning directly in CMakeLists.txt can be messy when you want to have multiple compilers supported and multiple warnings.
This PR follows the idea recommended by https://github.com/cpp-best-practices/ :
Use a separated CMake file with all compiler warnings, and export it as a function.
The function can receive compiler custom compiler flags too, so users will have a flexible build. The Warning as error is not enable by default, but can be when defining `-DWARNINGS_AS_ERRORS=ON`
=> Add separated compiler warnings cmake file

CMakePresets.json, CONTRIBUTING.md
Hello!
I just added how to build the project using CMake presets.
To avoid extra details about CMake options, I enabled build_testing by default.
In a next PR we could add a section about build customization and how to install using cmake. 
Other sections are still present, only are enhanced and follow a description.
=> Add how to build in contribution guide

.github/workflows/linux-clang-build.yml, .github/workflows/linux-gxx-build.yml, .github/workflows/linux-static-analysis.yml, .github/workflows/macos-clang-build.yml, .github/workflows/publish-docs.yml, .github/workflows/windows-msvc-build.yml
Hello!
This PR adds support of skipping the CI when changing only documentation and nothing more. For instance, when updating the README, or documentation folder (it only contains .md files).
I used the [paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) feature from Github Actions. 
closes #631
=> CI: Skip building when changing documentation only

.github/workflows/linux-clang-build.yml, CMakeLists.txt, README.md, examples/CMakeLists.txt, examples/README.md, examples/basic/CMakeLists.txt, examples/basic/main.cpp, examples/person/CMakeLists.txt, examples/person/main.cpp
This PR brings initial example built in this project, so people does not need to tests as reference.
In addition, there is a new cmake option, `BUILD_EXAMPLES` which is documented in the examples README.md. 
As CMake will produce those executables in subfolders of build/, I also added CMake targets to make easier to execute them by using cmake presets, without changing the directory.
To validate the changes, I added the example step in the linux clang build, because it's really fast.
closes #620
=> Add initial examples

include/faker-cxx/Helper.h, include/faker-cxx/Word.h, src/common/FormatHelper.cpp, src/common/FormatHelper.h, src/modules/person/Person.cpp, src/modules/word/Word.cpp, src/modules/word/data/Adjectives.h, src/modules/word/data/Adverbs.h, src/modules/word/data/All.h, src/modules/word/data/Conjunctions.h, src/modules/word/data/Interjections.h, src/modules/word/data/Nouns.h, src/modules/word/data/Prepositions.h, src/modules/word/data/Verbs.h, tests/modules/internet/InternetTest.cpp, tests/modules/word/WordTest.cpp
Use `std::string_view` where possible except for `words()`. Avoid allocating and shuffling data! Adding a header to combine all data together, organized by length once. Functions rewritten to retrieve by length (binary search) if possible later.
NOTE: check formatting, I use tabs, this library uses spaces, I think I fixed them all.
When initialized all the data structures could be `constexpr` or `constinit`. I brought in a constexpr quicksort (not mine) because `std::sort` is not constexpr until c++20.
=> refactor words

src/modules/location/LocationData.h
Done by commenting "// clang-format <[off/on]> " at the begin and end of the sections to be ignored by clang-format
=> Turned off clang-format for long string array in "LocationData.h"

include/faker-cxx/Database.h, src/modules/database/Database.cpp, src/modules/database/DatabaseData.h, tests/modules/database/DatabaseTest.cpp
Database module migration from class to functions within database namespace
#665
=> refactor: database module migrate

CHANGELOG.md, include/faker-cxx/Sport.h, src/modules/sport/Sport.cpp, src/modules/sport/SportData.h, tests/modules/sport/SportTest.cpp
sport module migration from class to functions within sport namespace
=> refactor: sport module migrate (#684)

CHANGELOG.md, include/faker-cxx/Vehicle.h, src/modules/vehicle/Vehicle.cpp, src/modules/vehicle/VehicleData.h, tests/modules/vehicle/VehicleTest.cpp
vehicle module migration from class to functions within vehicle namespace
changed function name from "vehicle" to "vehicleName" in vehicle module
changelog updated
#687
=> refactor: vehicle module migrate

examples/basic/main.cpp, include/faker-cxx/Location.h, src/modules/location/Location.cpp, src/modules/location/LocationData.h, tests/modules/location/LocationTest.cpp
- location module migration from class to functions within location namespace
#675
=> refactor: location module migrate

include/faker-cxx/Image.h, src/modules/image/Image.cpp, tests/modules/image/ImageTest.cpp
- image module migration from class to functions within image namespace
#674
=> refactor: image module migrate

include/faker-cxx/Lorem.h, src/modules/lorem/Lorem.cpp, src/modules/lorem/LoremData.h, tests/modules/lorem/LoremTest.cpp
migrated Lorem module from class to functions within lorem namespace
=> refactor: change lorem class to namespace  #676 

include/faker-cxx/Hacker.h, src/modules/hacker/Hacker.cpp, src/modules/hacker/HackerData.h, tests/modules/hacker/HackerTest.cpp
- hacker module migration from class to functions within hacker namespace
#671
=> refactor: hacker module

examples/basic/main.cpp, include/faker-cxx/Internet.h, src/modules/git/Git.cpp, src/modules/internet/Internet.cpp, src/modules/internet/InternetData.h, src/modules/person/Person.cpp, src/modules/system/System.cpp, tests/modules/internet/InternetTest.cpp, tests/modules/person/PersonTest.cpp
- internet module migration from class to functions within internet namespace
- modified reference to functions from internet module in all dependent modules
#673
=> refactor: internet module

include/faker-cxx/Finance.h, src/modules/finance/Finance.cpp, src/modules/finance/FinanceData.h, tests/modules/finance/FinanceTest.cpp
migrated finance module from class to functions within finance namespace
=> refactor: change finance class to namespace

.github/workflows/linux-clang-build.yml, .github/workflows/linux-gxx-build.yml, .github/workflows/linux-static-analysis.yml, .github/workflows/macos-clang-build.yml, .github/workflows/windows-msvc-build.yml
Hello!
This PR avoids running the CI when touching markdown files, LICENSE or anything the docs/ folder.
The current state in main branch is using a rule to avoid building only when pushing, not for pull requests. In order to apply same rule, we need to duplicate the [paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)
closes 643
=> ci: Skip when changing markdown only

src/common/StringHelper.cpp, src/common/StringHelper.h, src/modules/git/Git.cpp, src/modules/hacker/Hacker.cpp, src/modules/helper/Helper.cpp, src/modules/internet/Internet.cpp, src/modules/lorem/Lorem.cpp, src/modules/system/System.cpp, tests/common/StringHelperTest.cpp, tests/modules/color/ColorTest.cpp, tests/modules/commerce/CommerceTest.cpp, tests/modules/company/CompanyTest.cpp, tests/modules/date/DateTest.cpp, tests/modules/finance/FinanceTest.cpp, tests/modules/git/GitTest.cpp, tests/modules/image/ImageTest.cpp, tests/modules/internet/InternetTest.cpp, tests/modules/location/LocationTest.cpp, tests/modules/lorem/LoremTest.cpp, tests/modules/person/PersonTest.cpp, tests/modules/word/WordTest.cpp
- stringhelper module migration from class to functions within common namespace
- modified reference to functions and variables from stringhelper module in all dependent modules
#755
=> refactor: stringhelper module

README.md
The PR https://github.com/conan-io/conan-center-index/pull/24018 has been merged and now Faker-cxx is listed in Conan Center. Users can install a pre-built library faker-cxx from there (or build from souce)
The recipe is available here:
https://github.com/conan-io/conan-center-index/blob/master/recipes/faker-cxx/all/conanfile.py
Packages are hosted by JFrog's Artifactory instance and maintained by Conan team. 
The Conan Center search page is outdated, but as soon as it gets updated, faker-cxx should be listed there too: https://conan.io/center/recipes?value=faker-cxx
Meanwhile, is possible to find the package via CLI:
conan search -r conancenter faker-cxx
=> docs: Update README with how to install faker-cxx pre-built library using Conan

src/common/LuhnCheck.cpp, src/common/LuhnCheck.h, src/modules/helper/Helper.cpp, tests/common/LuhnCheckTest.cpp, tests/modules/finance/FinanceTest.cpp
- luhncheck module migration from class to functions within common namespace
- modified reference to functions and variables from luhncheck module in all dependent modules
#757
=> refactor: luhncheck module

src/modules/datatype/Datatype.cpp
- float to double typecast to comply with clang-tidy
=> refactor: datatype module

tests/modules/word/word_test.cpp
This pull request addresses issue #786 by adding additional test cases for the `word` module, to improve overall code coverage.
- The additions are based on the latest code coverage report, which can be found [here](https://app.codecov.io/github/cieslarmichal/faker-cxx/blob/main/src%2Fmodules%2Fword%2Fword.cpp), I've tried targeting previously uncovered lines in `word.cpp`
=> test: enhance code coverage of word module by adding additional testcases

tests/common/format_helper_test.cpp, tests/modules/word/word_test.cpp
This pull request addresses issue #781 by adding additional test cases for the `format_helper` module, to improve overall code coverage.
- The additions are based on the latest code coverage report, which can be found [here](https://app.codecov.io/github/cieslarmichal/faker-cxx/blob/main/src%2Fcommon%2FFormatHelper.cpp), I've tried targeting previously uncovered lines in `format_helper.cpp`
=> test: enhance code coverage of format helper module by adding additional testcases

CHANGELOG.md, include/faker-cxx/phone.h, src/modules/phone.cpp, tests/modules/phone_test.cpp
* changed function name from `number` (by format) to `phoneNumberByFormat` in phone module
* changed function name from `number` (by country) to `phoneNumberByCountry` in phone module
* modified test case for `phoneNumberByCountry` function
Fixes: #823
=> refactor: function name changed

include/faker-cxx/person.h
Added Locale enum based on table **Table A-1 Recommended Locales** from [https://docs.oracle.com/cd/E23824_01/html/E26033/glset.html](https://docs.oracle.com/cd/E23824_01/html/E26033/glset.html).
Closes #752.
=> feat: Introduce Locale enum

include/faker-cxx/phone.h, src/modules/phone.cpp, src/modules/phone_data.h, tests/modules/phone_test.cpp
* test case added to phone module for code coverage
Fixes: #811
=> test: phone module testcase added

CHANGELOG.md, include/faker-cxx/company.h, src/modules/company.cpp, tests/modules/company_test.cpp
* test case added to company module for code coverage
* function name changed from name to companyName
* changed companyName definition to take optional enum parameter
=> test: company module testcase added

include/faker-cxx/helper.h, src/modules/datatype.cpp
Running on latest GCC version and `ubuntu 22.04` I was getting conversion warnings from `arrayFormat(start, end)` overload specifically when used with `sortedSizeArrayElement` in `word_test.cpp`
Primary Warnings thrown:
In instantiation of function template specialization 'faker::word::sortedSizeArrayElement<__gnu_cxx::__normal_iterator<std::basic_string<char> *, std::vector<std::basic_string<char>>>>' /home/eric/github/faker-cxx/include/faker-cxx/helper.h:64:18: warning: implicit conversion changes signedness: 'unsigned long const' to '__gnu_cxx::__normal_iterator<std::basic_string<char> *, std::vector<std::basic_string<char>>>::difference_type' (aka 'long')
Fixed `arrayFormat` to enforce `input_iterator` concept in templates and fixed implicit conversion in index return of the function. …
=> fix: Made range arrayFormat overload more elegant + minor fixes

include/faker-cxx/helper.h, include/faker-cxx/word.h
`arrayElement(start, end)` overloads would fail when being used with bidrectional iterators or basically anything that wasnt a `random_access_iterator`, so I added overloads for both `random_access_iterator`'s and every other form.
Since random_access supports arithmetic we can just access index, but since every other iterator doesn't support we need to hand roll to the index. 
Even before I rewrote the function yesterday it still would've failed on `list` containers or non-random_access iterators.
=> fix: arrayElement overloads failing with non-arithmetic iterators

CMakeLists.txt, include/faker-cxx/helper.h, include/faker-cxx/word.h, src/common/algo_helper.h, src/modules/airline.cpp, src/modules/internet.cpp, src/modules/science.cpp, src/modules/string.cpp, src/modules/system.cpp, src/modules/word.cpp, tests/modules/word_test.cpp
With all of these functions using ranges instead of iterators, all you have to do is just pass the container straight since these cover all overloads.
Instead of using a pair of iterators you can use `ranges::subrange(start, end)` instead etc
These algos are also a lot more optimized and follow the best practices.
The first algo which is multipass is specifically for random_accsess and forward / sized ranges. Every other type of range that is basic like input_range uses a single pass approach.
=> refactor: Refactored all of randomElement related functions and iterators to use ranges instead

include/faker-cxx/esport.h, src/CMakeLists.txt, src/modules/esport.cpp, src/modules/esport_data.h, tests/CMakeLists.txt, tests/modules/esport_test.cpp
Add a new e-sport module with the following methods:
- std::string_view player();
- std::string_view team();
- std::string_view league();
- std::string_view event();
- std::string_view game();
=> feat: create e-sport module (#768)

README.md, include/faker-cxx/video.h, src/CMakeLists.txt, src/modules/video.cpp, src/modules/video_data.h, tests/CMakeLists.txt, tests/modules/video_test.cpp
Create video module with following methods:
- formatName
- fileExtension
- videoCodec
- audioCodec
- resolution
- aspectRatio
- videoUrl
=> feat: create video module (#770)

CHANGELOG.md, include/faker-cxx/vehicle.h, src/modules/vehicle.cpp, src/modules/vehicle_data.h, tests/modules/vehicle_test.cpp
=> feat: Added locale to vehicle module

include/faker-cxx/color.h, src/modules/color.cpp, tests/modules/color_test.cpp
This PR aims to tackle issue #935 
- Added hwb function in color.cpp and declared it in color.h.
- Wrote unit tests in color_test.cpp to verify functionality.
=> feat: add hwb function to Color module

include/faker-cxx/date.h, src/modules/date.cpp, tests/modules/date_test.cpp
Closes #937 
Added two `between` functions to the `Date` module, like: https://fakerjs.dev/api/date.html#between
One function to support two `ISO` Dates:
```cpp
std::string between(std::string from, std::string to, DateFormat dateFormat)
```
One function to support two `Timestamps`:
```cpp
std::string between(int64_t from, int64_t to, DateFormat dateFormat)
```
Made sure to write tests that cover edge cases, and added docs.
Run tests, and make sure they pass
Build and use `faker` in some `cpp` file and try out the new functions yourself, i.e.:
```cpp
faker::date::between("2021-01-01T00:00:00Z", "2022-01-01T00:00:00Z", DateFormat::ISO); // Returns a random date between Jan 1, 2021, and Jan 1, 2022, formatted as "2021-06-15T12:34:56Z"
faker::date::between("2021-01-01T00:00:00Z", …
```
=> feat: add between function to Date module

README.md
Regenerated the Table of Contents (ToC) in the README to reflect the current structure. Used doctoc for automation . Verified the links are working correctly.
=> docs: Regenerate Table of Contents in README  (issue no:  #929)

include/faker-cxx/esport.h, src/modules/esport.cpp, src/modules/esport_data.h, tests/modules/esport_test.cpp
refactor: add locale to esports module
=> refactor: add locale to esports module

src/modules/location.cpp
Fixed `shouldGenerateNearbyGPSCoordinateWithOriginInKilometers` and `shouldGenerateNearbyGPSCoordinateWithOriginInMiles`
Ran all tests locally using the following python script:
```
import subprocess
from tqdm import tqdm
def run_command(command):
process = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
output, error = process.communicate()
if process.returncode != 0:
print(f"Command failed with exit code {process.returncode}:")
print(error.decode())
return False
return output.decode()
def run_command_with_progress_bar(command, iterations):
for i in tqdm(range(iterations), desc="Running command", unit="iteration"):
output = run_command(command)
if output is None:
break
if __name__ == "__main__":
command = "ctest"
iterations = 100 …
```
=> fix: Fixed some flaky tests dues to floating point errors

include/faker-cxx/plant.h, src/modules/plant.cpp, src/modules/plant_data.h, tests/modules/plant_test.cpp
This PR introduces locale support in the plant module, with `enUS` set as the default. 
Fixes Issue: #898
Changes:
1. Locale Parameter for Plant Definitions
- Added `getPlantDefinition()` with locale as parameter to support locale-based plant data.
- Defaulted to `enUS` as a fallback for undefined or unsupported locales:
```cpp
const struct PlantDefinition& getPlantDefinition(Locale locale) {
switch (locale) {
default:
return enUSPlantDefinition;
}
}
```
2. Locale-Specific Naming in Plant Data
- Updated array naming for plant data, to reflect the locale:
```cpp
const auto enUSTrees = std::to_array<std::string_view> {/* data */};
```
3. Test Suite Updates
- Updated `plant_test` to incorporate the new locale parameter.
---
=> feat: add locale to plant module

tests/modules/commerce_test.cpp
This closes #907 
This PR improves the test coverage for the `ISBN10` function in `commerce.cpp` and the associated `commerce_test.cpp` file.
1. Updated `shouldGenerateIsbn10` : Updated to check only ISBNs without X.
2. Added `shouldGenerateIsbn10WithX` : Specifically tests for the check digit - X.
```cpp
std::string generatedIsbn10;
bool foundXCase = false;
for (size_t i = 0; i < 100 && !foundXCase; i++)
{
generatedIsbn10 = ISBN10();
if (generatedIsbn10[9] == 'X')
{
foundXCase = true;
}
}
if (!foundXCase)
{
generatedIsbn10 = "094339600X";
}
```
- `commerce.cpp` from 98% to 100%.
- `commerce_test.cpp` from 96% to 99%.
`Note`: While the tests achieve 99% coverage for `commerce_test.cpp`, the if `(!foundXCase)` branch in `shouldGenerateIsbn10WithX` is intentionally left uncovered to …
=> feat: improve codecov for commerce module

include/faker-cxx/helper.h, include/faker-cxx/location.h, include/faker-cxx/random_generator.h, src/modules/location.cpp, src/modules/location_data.h, src/modules/person.cpp, src/modules/string.cpp
This PR fixes formatting in recently changed files using `clang-format`.
=> fix: run clang format

.github/workflows/clang-format.yml
This closes #953 
This PR introduces a GitHub Action to check code formatting using clang-format.
- Runs only on push and pull_request events for `include/**/*.h`,`src/**/*.cpp` and `src/**/*.h` files.
- Cache check for `clang-format-18` to avoid re-installation if it is already installed.
- Validates formatting using git diff and fails the workflow if unformatted files are detected.
=> ci: add clang-format

include/faker-cxx/location.h, src/modules/location.cpp, src/modules/location_data.h, tests/modules/location_test.cpp
- Implemented random ordinal direction generation function.
- Added testing code for the ordinal direction generation function.
=> feat: added `ordinalDirection` generation function

include/faker-cxx/sport.h, src/modules/sport.cpp, src/modules/sport_data.h, tests/modules/internet_test.cpp, tests/modules/sport_test.cpp
Just add locale functionality to the sport module with 2 more groups of elements: es_AR and pt_BR. The functions map to en_US with the original data by default.
fix issue [https://github.com/cieslarmichal/faker-cxx/issues/897#top](https://github.com/cieslarmichal/faker-cxx/issues/897#top)
=> feat: add Locale to sport module

include/faker-cxx/image.h, src/modules/image.cpp, tests/modules/image_test.cpp
Summary of changes:
- Added a new method urlPicsumPhotos() to generate random images from the  https://picsum.photos website.
- Created necessary tests to ensure proper functionality.
- Renamed the imageUrl() method in urlLoremFlickr() to better distinguish between the different websites used for image generation.
=> fix: fix imageUrl in Image module to generate images from picsum photos #990

src/modules/location.cpp, tests/modules/location_test.cpp
LocationTest.shouldGenerateNearbyGPSCoordinateWithOriginInMiles was failing intermittently for two possible reasons:
1) The algorithm that generated lat,lon pairs in faker::location::nearbyGPSCoordinate was subject to error due to a spherical Earth assumption. This means it could potentially generate a lat,lon coordinate outside the radius parameter.
2) The algorithm that compared two lat,lon coordinates in location_test was subject to position error due to a spherical Earth assumption. This means it could erroneously calculate larger distances between coordinates than is true.
Replaced algorithms with Vincenty direct and inverse method respectively: https://en.wikipedia.org/wiki/Vincenty%27s_formulae
Ran (and passed) the tests (kilometers and miles) 1000 times each. Output the …
=> fix: improve geodetic coordinate generation and comparison 

include/faker-cxx/crypto.h, include/faker-cxx/string.h, src/modules/crypto.cpp, src/modules/string.cpp, tests/modules/crypto_test.cpp, tests/modules/string_test.cpp
add uuidv5 function to String module #1005,
add uuidv6 function to String module #1015.
=> feat: add uuid5, uuidv6 functions

.bazelrc, MODULE.bazel, WORKSPACE.bazel
- Replaced the `WORKSPACE.bazel` file with a `MODULE.bazel` file to migrate the project to Bzlmod for managing external dependencies.
- Defined dependencies for the following modules in `MODULE.bazel` using the `bazel_dep` function:
- `rules_foreign_cc` version `0.10.1`
- `googletest` version `1.14.0.bcr.1`
- `rules_cc` version `0.0.16`
- Removed the deprecated `WORKSPACE.bazel` file as it is no longer needed for managing external dependencies. **Backup of the removed `WORKSPACE.bazel` file has been kept in the project directory for reference and recovery.**
- Tested the project using `bazel build //...` and `bazel test //...`, confirming successful build and passing tests.
1. Migrated from `WORKSPACE.bazel` to `MODULE.bazel` for managing dependencies.
2. Updated the dependency …
=> feat: bzlmod migration phase 1 part 1

CMakeLists.txt, include/faker-cxx/base64.h, include/faker-cxx/image.h, src/CMakeLists.txt, src/modules/base64.cpp, src/modules/image.cpp, tests/CMakeLists.txt, tests/modules/airline_test.cpp, tests/modules/base64_test.cpp, tests/modules/crypto_test.cpp, tests/modules/image_test.cpp
This PR implements the `dataUri` function, which generates a random data URI containing either a URL-encoded SVG image or a Base64-encoded SVG image. It includes options for width, height, color, and type.
This feature allows users to easily generate SVG images in a data URI format, which is useful for embedding images directly in HTML.
I added unit tests for the `dataUri` function to ensure it generates valid SVG and Base64 URIs. All tests pass successfully.
Fixes #1024: add dataUri function to Image module
Currently, the function only supports basic colors. Future work could include support for gradients.
=> feat: Implement dataUri function for SVG generation

tests/modules/location_test.cpp
LocationTest.shouldGenerateNearbyGPSCoordinateWithOriginInMiles was failing intermittently between 1,000 <= 10,000 tests due to minor floating-point inaccuracies.
resolves #1030 
Ran and passed 5,000,000 tests just to be sure.
=> fix: LocationTest.shouldGenerateNearbyGPSCoordinateWithOriginInMiles not accounting for precision tolerance

.github/workflows/linux-bazel-build.yml, MODULE.bazel
This pull request updates the GitHub Actions workflow file `.github/workflows/linux-bazel-build.yml` by removing the `--enable_workspace` flag from the Bazel build and test commands. 
The `--enable_workspace` flag is no longer needed as part of the migration from the legacy `WORKSPACE` system to the newer `Bzlmod` (MODULE.bazel) dependency management system. 
The following changes were made:
1. **Removed `--enable_workspace` Flag**:
- The build command:
```bash
bazel build //:faker-cxx --enable_workspace
```
was updated to:
```bash
bazel build //:faker-cxx
```
- Similarly, the test command:
```bash
bazel build //tests:faker-cxx-ut --enable_workspace
bazel-bin/tests/faker-cxx-ut
```
was updated to:
```bash
bazel build //tests:faker-cxx-ut
bazel-bin/tests/faker-cxx-ut
```
2. **Ensured …
=> feat: remove --enable_workspace flag from bazel workflow

scripts/format_code.sh
Bash is located in different places on different systems (e.g. `/bin/bash` for me). This PR changes the _format_code.sh_ script to use a portable shebang that works on all  *nix platforms by finding bash in the `PATH`.
=> feat: use portable shebang for `format_code` bash script

include/faker-cxx/location.h, src/modules/location.cpp, tests/modules/location_test.cpp
Build and tests pass.
This PR adds an `mgrs(int precision = 4)` function, docs, and tests to the location submodule. The output is a syntactically (though possibly not semantically) valid [MGRS](https://en.wikipedia.org/wiki/Military_Grid_Reference_System) string that varies in precision based on its argument.
Not all outputs are valid grid references, and not all geospatial areas are covered. Specifically, areas near the poles are excluded from generation, since there is a higher probability that the grid reference will be invalid in those areas. Even so, this function will sometimes yield invalid MGRS coordinates.
=> feat: add random mgrs with specified precision

src/modules/commerce.cpp, tests/modules/commerce_test.cpp
Issue #1064
The Problem:
The issue arose because some product materials, like "Carbon Fiber," contained spaces. When the full product name was generated, it was split by spaces into parts. This caused the material to be split incorrectly into multiple parts. For example:
Original product name: "Gorgeous Carbon Fiber Chair"
When split by spaces:
"Gorgeous" (Adjective)
"Carbon" (Material)
"Fiber" (Material)
"Chair" (Name)
This resulted in four parts instead of the expected three, which broke the test because it was expecting exactly three components: Adjective, Material, and Name.
The Fix:
To prevent this issue, you changed the delimiter used for splitting the product name from a space (" ") to a pipe ("|") symbol. This ensures that multi-word materials like "Carbon Fiber" are treated as a …
=> fix: flaky Bug in CommerceTest.shouldGenerateProductFullName test - Issue #1064

include/faker-cxx/types/locale.h, src/modules/location.cpp, src/modules/location_data.h, tests/modules/location_test.cpp
This pull request introduces comprehensive data for **Lithuanian addresses**, expanding the `faker-cxx` library's functionality to generate realistic location-based information for the `lt_LT` locale.
* **Added `lt_LT` Locale Data**: Implemented new data structures for the Lithuanian locale within `location_data.h`.
* **Introduced Lithuanian Naming Conventions**: Included arrays for common Lithuanian street names, street suffixes (**`gatvė`**, **`prospektas`**, **`alėja`**), and city names.
* **Defined Address Formats**: Created format strings to correctly generate full street addresses, including those with building numbers and secondary address components (e.g., `butas`, `korpusas`).
* **Added Test Cases**: Fixed the associated unit tests to correctly validate the newly generated street …
=> feat: add Lithuania addresses (#456)
