cieslarmichal/faker-cxx

include/faker-cxx/types/Language.h, src/modules/person/Person.cpp, src/modules/person/PersonTest.cpp, src/modules/person/data/romanian/RomanianFirstNamesFemales.h, src/modules/person/data/romanian/RomanianFirstNamesMales.h, src/modules/person/data/romanian/RomanianLastNames.h
Added romanian language support for Person, according to TODO.md more language support was needed. Please review thank you.
=> added romanian lang support for person

src/modules/date/Date.cpp
I run the tests hundreds of times and it works better
=> Patched lower bound for birthdate random choice

include/faker-cxx/types/Language.h, src/modules/person/Person.cpp, src/modules/person/PersonTest.cpp, src/modules/person/data/finnish/FinnishFirstNamesFemales.h, src/modules/person/data/finnish/FinnishFirstNamesMales.h, src/modules/person/data/finnish/FinnishLastNames.h, src/modules/person/data/romanian/RomanianFirstNamesFemales.h, src/modules/person/data/romanian/RomanianFirstNamesMales.h, src/modules/person/data/romanian/RomanianLastNames.h
Added Finnish First and Last name support for Person. I also removed some duplicate names in Person::Romanian. I also formatted Person.cpp and PersonTest.cpp with clang-format.
=> removed romanian name duplicates and added finnish first and last names

.gitmodules, CMakeLists.txt, README.md, include/faker-cxx/Animal.h, src/modules/book/Book.cpp, src/modules/color/Color.cpp, src/modules/commerce/Commerce.cpp, src/modules/company/Company.cpp, src/modules/date/Date.cpp, src/modules/date/DateTest.cpp, src/modules/finance/Finance.cpp, src/modules/internet/Internet.cpp, src/modules/location/Location.cpp, src/modules/location/LocationTest.cpp, src/modules/location/data/france/FranceCities.h, src/modules/location/data/france/FranceStreetPrefixes.h, src/modules/lorem/Lorem.cpp, src/modules/person/Person.cpp
=> add fmt lib

src/modules/date/Date.cpp
required for std::put_time function
=> add missing iomanip header file in Date.cpp

include/faker-cxx/Person.h, src/modules/person/Person.cpp, src/modules/person/PersonTest.cpp, src/modules/person/data/Nationalities.h
Added nationality function and formatted files. Added `Nationalities.h` in `data`.
=> added nationality function

include/faker-cxx/Internet.h, src/modules/internet/Internet.cpp, src/modules/internet/InternetTest.cpp, src/modules/internet/data/EmailHosts.h, src/modules/internet/data/HttpRequestHeaders.h, src/modules/internet/data/HttpResponseHeaders.h, src/modules/person/data/nepalese/NepaleseFirstNamesMales.h
=> add generating http headers

src/modules/internet/Internet.cpp, src/modules/internet/InternetTest.cpp
=> improve password generation

include/faker-cxx/Internet.h, src/modules/internet/Internet.cpp, src/modules/internet/InternetTest.cpp, src/modules/internet/data/HttpMediaType.h
=> add http media type generation

include/faker-cxx/Helper.h, src/modules/helper/HelperTest.cpp, src/modules/string/String.cpp
=> feature: Implemented `Helper::setElement()`

.gitignore, include/faker-cxx/String.h, src/modules/string/String.cpp, src/modules/string/StringTest.cpp
=> feature: Implemented generation guarantees for `String::octal()`

include/faker-cxx/types/Country.h, src/modules/person/Person.cpp, src/modules/person/PersonTest.cpp, src/modules/person/data/latvia/LatvianFirstNames.h, src/modules/person/data/latvia/LatvianLastNames.h, src/modules/person/data/latvia/LatvianPeopleNames.h, src/modules/person/data/latvia/LatvianPrefixes.h, src/modules/person/data/latvia/LatvianSuffixes.h
=> add latvian people names

include/faker-cxx/String.h, src/modules/string/String.cpp, src/modules/string/StringTest.cpp, src/modules/string/data/Characters.h
=> feature: Implemented string guarantee for `String::hexadecimal()`

include/faker-cxx/String.h, src/modules/string/String.cpp, src/modules/string/StringTest.cpp, src/modules/string/data/Characters.h
=> feature: Implemented string guarantee for `String::alpha()`

include/faker-cxx/String.h, src/modules/string/String.cpp, src/modules/string/StringTest.cpp
=> feature: Implemented string guarantee for `String::alphanumeric()`

CMakeLists.txt, include/faker-cxx/Science.h, src/modules/science/Science.cpp, src/modules/science/ScienceTest.cpp, src/modules/science/data/elements.h, src/modules/science/data/units.h
Hello,
Raising a pull request with the code added for the Science module #158
With this module added, the user will be able to use Science.h as a include file and generate data for 2 additional user-defined datatypes 'ChemicalElement' and 'Unit'
Just like the other modules, Science::chemicalElement() function will return a random element from the periodic table.
Also using function Science::unit() function will return a random fundamental unit for measuring distance, time, mass, temp, current.
I have also added functions that can generate units specifically for distance, time, mass, temp, current respectively.
Regards,
Shardul
=> Science Module Complete

.gitmodules, CMakeLists.txt, include/faker-cxx/Structure.h, src/common/JsonHelper.cpp, src/common/JsonHelper.h, src/common/JsonHelperTest.cpp, src/modules/structure/Structure.cpp, src/modules/structure/StructureTest.cpp
This pull request introduces the new Structure Module, designed to address the requirements and objectives outlined in Issue #246. 
@cieslarmichal please review the changes and provide your insights or approval.
=> Add Structure module (json, csv)

include/faker-cxx/types/Country.h, src/modules/person/Person.cpp, src/modules/person/PersonTest.cpp, src/modules/person/data/bulgaria/BulgarianFirstNames.h, src/modules/person/data/bulgaria/BulgarianLastNames.h, src/modules/person/data/bulgaria/BulgarianPeopleNames.h, src/modules/person/data/bulgaria/BulgarianPrefixes.h, src/modules/person/data/bulgaria/BulgarianSuffixes.h, src/modules/structure/StructureTest.cpp
=> add bulgarian names

include/faker-cxx/Helper.h, include/faker-cxx/Person.h, include/faker-cxx/types/SsnCountry.h, src/modules/helper/Helper.cpp, src/modules/person/Person.cpp, src/modules/person/PersonTest.cpp, src/modules/person/data/SsnFormats.h
=> add generating ssn

CMakeLists.txt, include/faker-cxx/types/Country.h, src/common/FormatHelper.h, src/common/FormatHelperTest.cpp, src/modules/person/Person.cpp, src/modules/person/PersonTest.cpp, src/modules/person/data/iceland/IcelandicFirstNames.h, src/modules/person/data/iceland/IcelandicLastNames.h, src/modules/person/data/iceland/IcelandicPeopleNames.h
Hi,
Added people names from Iceland #305. 
Do let me know if this is fine or if it needs any changes ill do it!
Thank you.
=> Added Iceland people names.

include/faker-cxx/types/Country.h, src/modules/person/Person.cpp, src/modules/person/PersonTest.cpp, src/modules/person/data/palestine/PalestinianFirstNames.h, src/modules/person/data/palestine/PalestinianLastNames.h, src/modules/person/data/palestine/PalestinianPeopleNames.h
The PR:
- Fixed the guides link in README.
- Added people's names from Palestine #409.
Data is taken from [this website](https://firstnam.es/palestinian-territory). Please let me know if there are any issues. Thank you.
=> Add people name from Palestine 🇵🇸

src/modules/person/data/lebanon/LebanesePeopleNames.h
Fixed error in lebanesePeopleNames struct
=> fix lebanon people names struct

include/faker-cxx/Internet.h, src/modules/internet/Internet.cpp, src/modules/internet/InternetTest.cpp
testing every country (to me seemed like a lot and a waste of time since we're already testing two countries)
if it's a problem let me know and i can change it
=> added country parameter to Internet::username, also added testing

include/faker-cxx/types/Country.h, src/modules/location/LocationTest.cpp, src/modules/person/data/israel/IsraelisFirstNames.h, src/modules/person/data/israel/IsraelisLastNames.h, src/modules/science/data/ChemicalElements.h, src/modules/science/data/Units.h
=> fix israeli names

include/faker-cxx/Airline.h, include/faker-cxx/types/AirlineTypes.h, src/modules/airline/Airline.cpp, src/modules/airline/AirlineTest.cpp, src/modules/airline/data/Airlines.h, src/modules/airline/data/Airplanes.h, src/modules/airline/data/Airports.h, src/modules/airline/data/Seat.h, src/modules/structure/Structure.cpp, src/modules/structure/StructureTest.cpp
I wasn't sure if there was a way to make the structs be apart of `Airline` class, if you want to I can try finding a way to move them back as I'm not too sure if they're good just being apart of `faker`
=> Moved all Airline structs to AirlineTypes.h

include/faker-cxx/Airline.h, src/modules/airline/Airline.cpp, src/modules/airline/AirlineTest.cpp
Added follow unit tests:
- `Airline::flightNumber` without leading zeros
- `Airline::flightNumber` with leading zeros
- `Airline::flightNumberByRange`
=> Added unit tests to Airline::flightNumber

.gitmodules, include/faker-cxx/Commerce.h, src/modules/commerce/Commerce.cpp, src/modules/commerce/CommerceTest.cpp, src/modules/commerce/data/Commerce.h
Added the three mentioned functionalities in issue #483:
- paymentId
- paymentType
- paymentProvider
=> Added payment related functionalities to Commerce Module #483

include/faker-cxx/Git.h, src/modules/git/Git.cpp, src/modules/git/GitTest.cpp
author() added to Git Module.
returns Author {
name:
email:
}
=> Author added to Git Module. Resolves #490

include/faker-cxx/Phone.h
=> Add missing doxygen documentation in phone module

include/faker-cxx/Image.h, src/modules/image/Image.cpp, src/modules/image/ImageTest.cpp, src/modules/image/data/Type.h
Added image type functionality and  fixed typos in the examples
=> Added image type functionality

include/faker-cxx/Color.h, src/modules/color/Color.cpp, src/modules/color/ColorTest.cpp
Added `hsb` and `hsv` functions to Color module and unit-tests
=> Added hsb and hsv functions to Color module

include/faker-cxx/Finance.h, src/modules/finance/Finance.cpp, src/modules/finance/FinanceTest.cpp, src/modules/finance/data/CreditCardTypeNames.h
Added creditCardTypes method to Finance module
Fixes the issue #478
=> Added creditCardTypes method to return a random credit card type.

include/faker-cxx/types/Country.h, src/modules/person/Person.cpp, src/modules/person/PersonTest.cpp, src/modules/person/data/liechtenstein/LiechtensteinerPeopleFirstNames.h, src/modules/person/data/liechtenstein/LiechtensteinerPeopleLastNames.h, src/modules/person/data/liechtenstein/LiechtensteinerPeopleNames.h
This update is done in reference to issue #404 Add people names from Liechtenstein #404
=> Added liechtensteiner People Names

src/modules/person/data/luxembourg/LuxembourgFirstNames.h, src/modules/person/data/luxembourg/LuxembourgLastNames.h, src/modules/person/data/luxembourg/LuxembourgPeopleNames.h
Add people names from Luxembourg #405
by Dorjderem
=> luxembourg names

src/common/StringHelper.cpp, src/common/StringHelper.h, src/modules/internet/Internet.cpp, src/modules/lorem/Lorem.cpp, src/modules/system/System.cpp, src/modules/word/Word.cpp, tests/common/StringHelperTest.cpp
- StringHelper::join() function is modified to take string_view as parameter
- Updated word() in lorem Module function to return string_view.
- Introduced a new StringHelper::joinString() function to handle vector of string arguments.
=>  Modified stringHelper::Join to use string_view

README.md
I have added the table of contents to the repo as requested. Please review. Thank you!
=> Added table of contents in README (#641)

README.md
added general plant type which contains seven types of plants, I think there's no need to write all types.
=> added plant Module to README

docs/guides/gcc-compilation-guide.md
Updated binary generated location after the build
=> Fix gcc compilation step-5 in the guide

include/faker-cxx/VideoGame.h, src/modules/videoGame/VideoGame.cpp, src/modules/videoGame/VideoGameData.h, tests/modules/videoGame/VideoGameTest.cpp
#688 videogame module migration from class to functions within videogame namespace
=> refactor: videogame module migrate (#688)

include/faker-cxx/Food.h, src/modules/food/Food.cpp, src/modules/food/FoodData.h, tests/modules/food/FoodTest.cpp
- food module migration from class to functions within food namespace
#669
=> refactor: food module migrate

include/faker-cxx/Music.h, src/modules/music/Music.cpp, tests/modules/music/MusicTest.cpp
- music module migration from class to functions within music namespace
#679
=> refactor: music module migrate

include/faker-cxx/Phone.h, src/modules/phone/Phone.cpp, tests/modules/phone/PhoneTest.cpp
- phone module migration from class to functions within phone namespace
#682
=> refactor: phone module migrate

examples/basic/main.cpp, include/faker-cxx/String.h, src/modules/airline/Airline.cpp, src/modules/color/Color.cpp, src/modules/commerce/Commerce.cpp, src/modules/database/Database.cpp, src/modules/finance/Finance.cpp, src/modules/git/Git.cpp, src/modules/internet/Internet.cpp, src/modules/person/Person.cpp, src/modules/string/String.cpp, src/modules/string/StringData.h, src/modules/system/System.cpp, src/modules/vehicle/Vehicle.cpp, tests/modules/color/ColorTest.cpp, tests/modules/commerce/CommerceTest.cpp, tests/modules/database/DatabaseTest.cpp, tests/modules/finance/FinanceTest.cpp, tests/modules/internet/InternetTest.cpp, tests/modules/location/LocationTest.cpp, tests/modules/string/StringTest.cpp
- string module migration from class to functions within string namespace
- modified reference to functions and variables from string module in all dependent modules
#685
=> refactor: string module

README.md
Added the instructions of building with Bazel in the README.
=> docs: building with Bazel #762

src/common/FormatHelper.cpp, src/common/FormatHelper.h, src/modules/color/Color.cpp, src/modules/commerce/Commerce.cpp, src/modules/company/Company.cpp, src/modules/date/Date.cpp, src/modules/finance/Finance.cpp, src/modules/git/Git.cpp, src/modules/image/Image.cpp, src/modules/internet/Internet.cpp, src/modules/location/Location.cpp, src/modules/lorem/Lorem.cpp, src/modules/person/Person.cpp, src/modules/string/String.cpp, src/modules/system/System.cpp, src/modules/vehicle/Vehicle.cpp, tests/common/FormatHelperTest.cpp
- formathelper module migration from class to functions within common namespace
- modified reference to functions and variables from formathelper module in all dependent modules
#756
=> refactor: formathelper module

.github/workflows/linux-clang-build.yml, .github/workflows/linux-static-analysis.yml, CMakeLists.txt, tests/CMakeLists.txt
Hello! I just integrated the Codecov to my fork, using Github actions, and it's working now.
You can check the current PR https://github.com/uilianries/faker-cxx/pull/4 as validation.
The coverage result is available at https://app.codecov.io/gh/uilianries/faker-cxx/commit/1d6ca6961f69bee9bab0f14f0907a34406cb2b3c
Some important configurations:
- Need to integrate Codecov to the project: https://github.com/marketplace/actions/codecov
- Once you have a login in Codecov, you will need to add the secret token: https://app.codecov.io/gh/cieslarmichal/faker-cxx/settings
Currently, the coverage is checking the library only, not tests.
fixes #598
=> ci: Fix code coverage and publish on Codecov

README.md
Added the Conan Center badge in README.md, so users can find https://conan.io/center/recipes/faker-cxx easily.
=> docs: Add Conan Center badge

tests/modules/airline/AirlineTest.cpp
- testcase added for airline module for code coverage
#783
=> test: airline testcase

tests/common/StringHelperTest.cpp
- testcase added for stringhelper module for code coverage
#782
=> test: stringhelper testcase

tests/modules/helper/HelperTest.cpp
- testcase added for helper module for code coverage
#785
=> test: helper testcase

.gitignore, include/faker-cxx/Helper.h, include/faker-cxx/Person.h, include/faker-cxx/RandomGenerator.h, src/common/AlgoHelper.h, src/modules/color/Color.cpp, src/modules/commerce/Commerce.cpp, src/modules/company/Company.cpp, src/modules/date/Date.cpp, src/modules/finance/Finance.cpp, src/modules/git/Git.cpp, src/modules/hacker/Hacker.cpp, src/modules/helper/Helper.cpp, src/modules/image/Image.cpp, src/modules/internet/Internet.cpp, src/modules/location/Location.cpp, src/modules/lorem/Lorem.cpp, src/modules/person/Person.cpp, src/modules/phone/Phone.cpp, src/modules/string/String.cpp, src/modules/system/System.cpp, tests/modules/git/GitTest.cpp, tests/modules/internet/InternetTest.cpp
When running `cppcheck` on main branch it results in several errors.
This PR fixes all current errors.
=> ci: Fix cppcheck errors

src/modules/git/Git.cpp, tests/modules/git/GitTest.cpp
- testcase added for git module for code coverage
- modified commit date function to just return ISO date format
#784
=> test: git testcase added

tests/modules/system/system_test.cpp
- testcase added for system module for code coverage
Fixes: #812
=> test: system testcase added

tests/modules/system/system_test.cpp
- testcase added for system module for code coverage
=> test: System testcase codecov

src/modules/hacker_data.h, tests/modules/hacker_test.cpp
* test case added for hacker module for codecoverage
Fixes: #808
=> test: hacker module testcase added

tests/modules/internet_test.cpp
* test case added to internet module for code coverage
Fixes: #809
=> test: internet module testcase added

include/faker-cxx/finance.h, src/modules/finance.cpp, tests/modules/finance_test.cpp
* test case added to finance module for code coverage
=> test: finance module testcase added

include/faker-cxx/word.h, src/modules/word.cpp, tests/CMakeLists.txt, tests/modules/word_data_test.cpp, tests/modules/word_test.cpp
I've moved `sortedSizeArrayElement()` definition to `word.h`, so it can be included in `word_test.cpp` and tested in isolation.
Closes #813.
=> test: increase test coverage for word module

include/faker-cxx/word.h, tests/modules/word_test.cpp
* test case added to word module for codecoverage.
* existing test case name changed for distinction
=> test: word module codecoverage

CHANGELOG.md, include/faker-cxx/git.h, src/modules/git.cpp, tests/modules/git_test.cpp
* test case added to git module for code coverage
* changed function to accept enum parameter
* changelog updated
=> test: git module codecov

src/modules/datatype.cpp, tests/modules/datatype_test.cpp
* testcase added to datatype module for code coverage
Fixes: #806
=> test: datatype testcase added

include/faker-cxx/airline.h, include/faker-cxx/commerce.h, include/faker-cxx/company.h, include/faker-cxx/database.h, include/faker-cxx/date.h, include/faker-cxx/hacker.h, include/faker-cxx/image.h, include/faker-cxx/location.h, include/faker-cxx/person.h, include/faker-cxx/vehicle.h
=> fix: fixing missing includes

tests/modules/crypto_test.cpp
* testcase added to crypto module for code coverage
=> test: crypto module testcase

include/faker-cxx/types/locale.h
=> feat: locale: add missing locales to enum

docs/guides/gcc-compilation-guide.md
Included additional directory for running unit tests
=> docs: Update gcc-compilation-guide.md

tests/common/string_helper_test.cpp
test: added test for single string
for: #906 
CheckList
[x] Ran test suit
=> test: added new single string test

include/faker-cxx/number.h, include/faker-cxx/string.h, src/modules/number.cpp, src/modules/string.cpp, tests/modules/number_test.cpp, tests/modules/string_test.cpp
=> refactor: move "octal" from string to number module

include/faker-cxx/types/locale.h, src/common/algo_helper.h, src/modules/helper.cpp, src/modules/location.cpp, src/modules/location_data.h, tests/modules/helper_test.cpp, tests/modules/location_test.cpp
feat: Added UK location data
test: Created UK address tests. Created and modified tests to check for the generated alphanumeric postcodes. Added test for new letter replacement algorithm.
=> feat: Added UK location data

src/modules/weather.cpp, src/modules/weather_data.h, tests/modules/weather_test.cpp
* added weather descriptions to finland, germany, poland, czechia and france
fixed: #915
=> chore: added weather descriptions

include/faker-cxx/video_game.h, src/modules/video_game.cpp, src/modules/video_game_data.h, tests/modules/video_game_test.cpp
* add locale to video game module
fixed: #901
=> refactor: add locale

tests/modules/person_test.cpp
Fixed the Codecov errors occurring within the screenshot of the issue, errors no longer occur on my end, and tests run smoothly.
=> test: Fixed Codecov errors in person test. Issue: #909

include/faker-cxx/animal.h, src/modules/animal.cpp, src/modules/animal_data.h, tests/modules/animal_test.cpp
Fixes issue #888 
Adds locale to the animal module
=> refactor: add locale to animal module

src/modules/location.cpp, src/modules/location_data.h, tests/modules/location_test.cpp
solves: #131 
Adds location addresses for Mexico.
=> feat: added mexico location data

src/modules/location.cpp, src/modules/location_data.h, tests/modules/location_test.cpp
feat: added Palestine location data 
* added Palestine location data
* added test case
=> feat: added Palestine location data 

src/modules/string.cpp, tests/modules/string_test.cpp
=> feat: add uuidv7 functions

README.md
I forgot to update README.md when submitting #1044.
=> docs: add mgrs to README.md

include/faker-cxx/number.h, src/modules/number.cpp, tests/modules/number_test.cpp
Added a roman function to convert integers to Roman numerals.
Implemented basic unit tests for the roman function to validate its behavior for basic edges cases.
Validated that all unit tests passed successfully after adding the feature.
This is my first contribution to the project. If I have made any mistakes or missed any necessary steps, I am happy to make corrections and improve. Please feel free to let me know how I can improve.
=> feat: Romannumber

src/modules/location.cpp, src/modules/location_data.h, tests/modules/location_test.cpp
=> feat: Add Turkey location addresses issue #140

src/modules/location.cpp, src/modules/location_data.h, tests/modules/location_test.cpp
=> feat: Add Japan location addresses Issue #133

include/faker-cxx/esport.h, src/modules/esport.cpp, src/modules/esport_data.h, tests/modules/esport_test.cpp
=> feat: Add Code to Generate Esport Organizers

README.md, include/faker-cxx/education.h, src/modules/education.cpp, src/modules/education_data.h, tests/modules/education_test.cpp
=> feat: add education and Update Read Me File

src/modules/location.cpp, src/modules/location_data.h, tests/modules/location_test.cpp
Added location address data for Hungary to the dataset
Closes #143
=> feat: add Hungary addresses
